### PR TITLE
Add a github action

### PR DESCRIPTION
**Pull request by zanderso**

### CODE REVIEW

**Comment by zanderso** [comment]
@bdero No idea how to test this other than landing it.

If this is too hard, we might also just do this in our regular CI, but I was hoping this setup could be part of the example.

**Comment by bdero** [comment]
Definitely agree we should have the build going as a precheck on this repo. Once we get other toolchains going, we can test those too. :)

**Review by bdero — APPROVED** [review]

**Comment by bdero** [comment]
@zanderso Iterated on this tonight and eventually got it building!
image

Had to disable the macos target because the LLVM action doesn't support macOS (it runs a script that explicitly fails when darwin is detected), but we can probably just come back around and install clang packages ourselves...

Also, not sure why the workflow isn't triggering on pushes/PRs, but I was able to trigger manual runs with the GH CLI after adding the `workflow_dispatch` trigger.

**Comment by zanderso** [comment]
Nice!

**Pull request merged**
